name: Create a pull request by repository_dispatch

on:
  repository_dispatch:
    types: [update-version]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update xxxx file
          delete-branch: true
          title: Update xxxx file
          reviewers: kazuma0129
