name: Create a pull request by repository_dispatch

on:
  repository_dispatch:
    types: [update-version]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1.8
        id: generate-gtihub-token
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install React Latest Version
        if: github.event.client_payload.distribution_env == 'production'
        run: |
          read VERSION_PRD < <(npm dist-tag ls react | awk '/latest:/ {prod=$2} END {print prod}')
          yarn add -E \
            react@$VERSION_PRD
      - name: Install React Candidates Version
        if: github.event.client_payload.distribution_env == 'candidates'
        run: |
          read VERSION_CANARY VERSION_RC < <(npm dist-tag ls react | awk '/canary:/ {canary=$2} /next:/ {nxt=$2} END {print canary, nxt}')
          yarn add -E \
            react/canary@npm:react@$VERSION_CANARY \
            react/next@npm:react@$VERSION_NEXT
      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "HAS_DIFF=false" >> $GITHUB_ENV
          else
            echo "HAS_DIFF=true" >> $GITHUB_ENV
          fi
      - uses: peter-evans/create-pull-request@v5
        if: env.HAS_DIFF == 'true'
        with:
          commit-message: Bump react ${{ github.event.client_payload.distribution_env }} to latest version
          delete-branch: true
          title: Bump react
          reviewers: kazuma0129
        env: 
          GITHUB_TOKEN: ${{ steps.generate-gtihub-token.outputs.token }}
